### ISSUE TITLE
Support Billing

### ISSUE THREAD

**Issue by devhoussam1998** [raugadh/fila-starter#11]
Try to support billing maybe you can use [Lemon Squeezy](https://github.com/lmsqueezy/laravel) or [Laravel cashier with stripe](https://github.com/maartenpaauw/filament-cashier-billing-provider).

**Comment by raugadh** [comment]
Hey, Billing is not planned to be added as majority of projects I work with are basic CMS website, the intention of this projects is to provide the most basic scaffolding to work on variety of projects. Adding billing will narrow that flexibility.

you can always fork the project. Thanks
